name: UniversalDownloader
options:
  bundleIdPrefix: com.universaldownloader
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
targets:
  UniversalDownloader:
    type: application
    platform: iOS
    sources:
      - UniversalDownloader
      - Shared
    scheme:
      testTargets:
        - UniversalDownloaderTests
        - UniversalDownloaderUITests
      gatherCoverageData: true
      coverageTargets:
        - UniversalDownloader
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ct4nk3r.universaldownloader
        DEVELOPMENT_TEAM: G5FY6A6X2G
        INFOPLIST_FILE: UniversalDownloader/Info.plist
        CODE_SIGN_ENTITLEMENTS: UniversalDownloader/UniversalDownloader.entitlements
    dependencies:
      - target: ShareExtension
  UniversalDownloaderTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - UniversalDownloaderTests
    dependencies:
      - target: UniversalDownloader
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
  UniversalDownloaderUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - UniversalDownloaderUITests
    dependencies:
      - target: UniversalDownloader
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
  ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - ShareExtension
      - Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ct4nk3r.universaldownloader.ShareExtension
        DEVELOPMENT_TEAM: G5FY6A6X2G
        INFOPLIST_FILE: ShareExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: ShareExtension/ShareExtension.entitlements
